
package com.tekla.webservices._2015._05.person;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-06-27T12:42:34.654+03:00
 * Generated source version: 3.0.3
 * 
 */
public final class IPerson_BasicHttpBindingIPerson_Client {

    private static final QName SERVICE_NAME = new QName("http://tekla.com/webservices/2015/05/Person", "Person");

    private IPerson_BasicHttpBindingIPerson_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Person.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Person ss = new Person(wsdlURL, SERVICE_NAME);
        IPerson port = ss.getBasicHttpBindingIPerson();  
        
        {
        System.out.println("Invoking getPersonSpouseByIdentityCode...");
        java.lang.String _getPersonSpouseByIdentityCode_key = "";
        java.lang.String _getPersonSpouseByIdentityCode_identityCode = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonSpouseResult _getPersonSpouseByIdentityCode__return = port.getPersonSpouseByIdentityCode(_getPersonSpouseByIdentityCode_key, _getPersonSpouseByIdentityCode_identityCode);
        System.out.println("getPersonSpouseByIdentityCode.result=" + _getPersonSpouseByIdentityCode__return);


        }
        {
        System.out.println("Invoking getPersonsByAddress...");
        java.lang.String _getPersonsByAddress_key = "";
        java.lang.String _getPersonsByAddress_streetName = "";
        java.lang.String _getPersonsByAddress_addressNumberInt1 = "";
        java.lang.String _getPersonsByAddress_addressNumberInt2 = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonSearchResult _getPersonsByAddress__return = port.getPersonsByAddress(_getPersonsByAddress_key, _getPersonsByAddress_streetName, _getPersonsByAddress_addressNumberInt1, _getPersonsByAddress_addressNumberInt2);
        System.out.println("getPersonsByAddress.result=" + _getPersonsByAddress__return);


        }
        {
        System.out.println("Invoking getPersonAdditionalInfoByIdentityCode...");
        java.lang.String _getPersonAdditionalInfoByIdentityCode_key = "";
        java.lang.String _getPersonAdditionalInfoByIdentityCode_identityCode = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonAdditionalInfoResult _getPersonAdditionalInfoByIdentityCode__return = port.getPersonAdditionalInfoByIdentityCode(_getPersonAdditionalInfoByIdentityCode_key, _getPersonAdditionalInfoByIdentityCode_identityCode);
        System.out.println("getPersonAdditionalInfoByIdentityCode.result=" + _getPersonAdditionalInfoByIdentityCode__return);


        }
        {
        System.out.println("Invoking getPersonPropertiesByIdentityCode...");
        java.lang.String _getPersonPropertiesByIdentityCode_key = "";
        java.lang.String _getPersonPropertiesByIdentityCode_identityCode = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonPropertiesResult _getPersonPropertiesByIdentityCode__return = port.getPersonPropertiesByIdentityCode(_getPersonPropertiesByIdentityCode_key, _getPersonPropertiesByIdentityCode_identityCode);
        System.out.println("getPersonPropertiesByIdentityCode.result=" + _getPersonPropertiesByIdentityCode__return);


        }
        {
        System.out.println("Invoking getPersonAddressByIdentityCode...");
        java.lang.String _getPersonAddressByIdentityCode_key = "";
        java.lang.String _getPersonAddressByIdentityCode_identityCode = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonAddressResult _getPersonAddressByIdentityCode__return = port.getPersonAddressByIdentityCode(_getPersonAddressByIdentityCode_key, _getPersonAddressByIdentityCode_identityCode);
        System.out.println("getPersonAddressByIdentityCode.result=" + _getPersonAddressByIdentityCode__return);


        }
        {
        System.out.println("Invoking getPersonRelationsByIdentityCode...");
        java.lang.String _getPersonRelationsByIdentityCode_key = "";
        java.lang.String _getPersonRelationsByIdentityCode_identityCode = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonRelationsResult _getPersonRelationsByIdentityCode__return = port.getPersonRelationsByIdentityCode(_getPersonRelationsByIdentityCode_key, _getPersonRelationsByIdentityCode_identityCode);
        System.out.println("getPersonRelationsByIdentityCode.result=" + _getPersonRelationsByIdentityCode__return);


        }
        {
        System.out.println("Invoking getPersonsByName...");
        java.lang.String _getPersonsByName_key = "";
        java.lang.String _getPersonsByName_surname = "";
        java.lang.String _getPersonsByName_firstName = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonSearchResult _getPersonsByName__return = port.getPersonsByName(_getPersonsByName_key, _getPersonsByName_surname, _getPersonsByName_firstName);
        System.out.println("getPersonsByName.result=" + _getPersonsByName__return);


        }
        {
        System.out.println("Invoking getPersonsByIdentityCode...");
        java.lang.String _getPersonsByIdentityCode_key = "";
        java.lang.String _getPersonsByIdentityCode_identityCode = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonSearchResult _getPersonsByIdentityCode__return = port.getPersonsByIdentityCode(_getPersonsByIdentityCode_key, _getPersonsByIdentityCode_identityCode);
        System.out.println("getPersonsByIdentityCode.result=" + _getPersonsByIdentityCode__return);


        }
        {
        System.out.println("Invoking getPersonsByUpdateDate...");
        java.lang.String _getPersonsByUpdateDate_key = "";
        java.lang.String _getPersonsByUpdateDate_startDate = "";
        java.lang.String _getPersonsByUpdateDate_endDate = "";
        org.datacontract.schemas._2004._07.tekla_gis.PersonByUpdateDateSearchResult _getPersonsByUpdateDate__return = port.getPersonsByUpdateDate(_getPersonsByUpdateDate_key, _getPersonsByUpdateDate_startDate, _getPersonsByUpdateDate_endDate);
        System.out.println("getPersonsByUpdateDate.result=" + _getPersonsByUpdateDate__return);


        }

        System.exit(0);
    }

}
