package org.xroad.metadata;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.xroad.xml.xrd.XRoadServiceIdentifierType;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-10-26T17:39:25.357+03:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://metadata.x-road.eu/", name = "metaServicesPort")
@XmlSeeAlso({org.xroad.xml.xrd.ObjectFactory.class, ObjectFactory.class})
public interface MetaServicesPort {

    /**
     * 
     *             
     */
    @WebMethod
    @RequestWrapper(localName = "allowedMethods", targetNamespace = "http://metadata.x-road.eu/", className = "org.xroad.metadata.AllowedMethods")
    @ResponseWrapper(localName = "allowedMethodsResponse", targetNamespace = "http://metadata.x-road.eu/", className = "org.xroad.metadata.AllowedMethodsResponse")
    @WebResult(name = "serviceCode", targetNamespace = "")
    public java.util.List<XRoadServiceIdentifierType> allowedMethods();

    /**
     * 
     *             
     */
    @WebMethod
    @RequestWrapper(localName = "listMethods", targetNamespace = "http://metadata.x-road.eu/", className = "org.xroad.metadata.ListMethods")
    @ResponseWrapper(localName = "listMethodsResponse", targetNamespace = "http://metadata.x-road.eu/", className = "org.xroad.metadata.ListMethodsResponse")
    @WebResult(name = "serviceCode", targetNamespace = "")
    public java.util.List<XRoadServiceIdentifierType> listMethods();
}
