package org.xroad.metadata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-10-26T17:39:25.362+03:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "producerPortService", 
                  wsdlLocation = "file:/C:/Kehitys/Palveluväylä/Testiympäristö/VRK/centralServices.wsdl",
                  targetNamespace = "http://metadata.x-road.eu/") 
public class ProducerPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://metadata.x-road.eu/", "producerPortService");
    public final static QName MetaServicesPortSoap11 = new QName("http://metadata.x-road.eu/", "metaServicesPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Kehitys/Palveluväylä/Testiympäristö/VRK/centralServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProducerPortService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Kehitys/Palveluväylä/Testiympäristö/VRK/centralServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProducerPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProducerPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProducerPortService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MetaServicesPort
     */
    @WebEndpoint(name = "metaServicesPortSoap11")
    public MetaServicesPort getMetaServicesPortSoap11() {
        return super.getPort(MetaServicesPortSoap11, MetaServicesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetaServicesPort
     */
    @WebEndpoint(name = "metaServicesPortSoap11")
    public MetaServicesPort getMetaServicesPortSoap11(WebServiceFeature... features) {
        return super.getPort(MetaServicesPortSoap11, MetaServicesPort.class, features);
    }

}
