package fi.vrk.xml.ws.vtj.vtjkysely._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-11-16T16:40:30.372+02:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", name = "ISoSoAdapterService60")
@XmlSeeAlso({ObjectFactory.class, org.xroad.xml.xrd.ObjectFactory.class})
public interface ISoSoAdapterService60 {

    @WebMethod(operationName = "HenkilonTunnusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/HenkilonTunnusKyselyResponse")
    @RequestWrapper(localName = "HenkilonTunnusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyReqBody")
    @ResponseWrapper(localName = "HenkilonTunnusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyResBody")
    public void henkilonTunnusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<HenkiloTunnusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<HenkiloTunnusKyselyResType> response
    );

    @WebMethod(operationName = "HaeTuotteenSkeema")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/HaeTuotteenSkeemaResponse")
    @RequestWrapper(localName = "HaeTuotteenSkeema", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaReqBody")
    @ResponseWrapper(localName = "HaeTuotteenSkeemaResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaResBody")
    public void haeTuotteenSkeema(
        @WebParam(name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaReqBodyTiedot request,
        @WebParam(mode = WebParam.Mode.OUT, name = "reguest", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<TuotteenSkeemaReqBodyTiedot> reguest,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<TuotteenSkeemaResType> response
    );
}
