
package fi.vrk.xml.ws.vtj.vtjkysely._1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-11-16T16:40:30.327+02:00
 * Generated source version: 3.0.3
 * 
 */
public final class ISoSoAdapterService60_BasicHttpBindingISoSoAdapterService60_Client {

    private static final QName SERVICE_NAME = new QName("http://xml.vrk.fi/ws/vtj/vtjkysely/1", "SoSoAdapterService60");

    private ISoSoAdapterService60_BasicHttpBindingISoSoAdapterService60_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SoSoAdapterService60.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SoSoAdapterService60 ss = new SoSoAdapterService60(wsdlURL, SERVICE_NAME);
        ISoSoAdapterService60 port = ss.getBasicHttpBindingISoSoAdapterService60();  
        
        {
        System.out.println("Invoking henkilonTunnusKysely...");
        fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyReqBodyTiedot _henkilonTunnusKysely_requestVal = null;
        javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyReqBodyTiedot> _henkilonTunnusKysely_request = new javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyReqBodyTiedot>(_henkilonTunnusKysely_requestVal);
        javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyResType> _henkilonTunnusKysely_response = new javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.HenkiloTunnusKyselyResType>();
        port.henkilonTunnusKysely(_henkilonTunnusKysely_request, _henkilonTunnusKysely_response);

        System.out.println("henkilonTunnusKysely._henkilonTunnusKysely_request=" + _henkilonTunnusKysely_request.value);
        System.out.println("henkilonTunnusKysely._henkilonTunnusKysely_response=" + _henkilonTunnusKysely_response.value);

        }
        {
        System.out.println("Invoking haeTuotteenSkeema...");
        fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaReqBodyTiedot _haeTuotteenSkeema_request = null;
        javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaReqBodyTiedot> _haeTuotteenSkeema_reguest = new javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaReqBodyTiedot>();
        javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaResType> _haeTuotteenSkeema_response = new javax.xml.ws.Holder<fi.vrk.xml.ws.vtj.vtjkysely._1.TuotteenSkeemaResType>();
        port.haeTuotteenSkeema(_haeTuotteenSkeema_request, _haeTuotteenSkeema_reguest, _haeTuotteenSkeema_response);

        System.out.println("haeTuotteenSkeema._haeTuotteenSkeema_reguest=" + _haeTuotteenSkeema_reguest.value);
        System.out.println("haeTuotteenSkeema._haeTuotteenSkeema_response=" + _haeTuotteenSkeema_response.value);

        }

        System.exit(0);
    }

}
