package fi.vrk.xml.ws.vtj.vtjkysely._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-11-16T16:40:30.379+02:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "SoSoAdapterService60", 
                  wsdlLocation = "file:/C:/Kehitys/Palveluväylä/Testiympäristö/VRK/HenkilonTunnuskysely.wsdl",
                  targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1") 
public class SoSoAdapterService60 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xml.vrk.fi/ws/vtj/vtjkysely/1", "SoSoAdapterService60");
    public final static QName BasicHttpBindingISoSoAdapterService60 = new QName("http://xml.vrk.fi/ws/vtj/vtjkysely/1", "BasicHttpBinding_ISoSoAdapterService60");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Kehitys/Palveluväylä/Testiympäristö/VRK/HenkilonTunnuskysely.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoSoAdapterService60.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Kehitys/Palveluväylä/Testiympäristö/VRK/HenkilonTunnuskysely.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoSoAdapterService60(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoSoAdapterService60(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoSoAdapterService60() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISoSoAdapterService60
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoSoAdapterService60")
    public ISoSoAdapterService60 getBasicHttpBindingISoSoAdapterService60() {
        return super.getPort(BasicHttpBindingISoSoAdapterService60, ISoSoAdapterService60.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoSoAdapterService60
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoSoAdapterService60")
    public ISoSoAdapterService60 getBasicHttpBindingISoSoAdapterService60(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingISoSoAdapterService60, ISoSoAdapterService60.class, features);
    }

}
