package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-06-27T11:40:20.037+03:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SoSoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SoSoSoap {

    @WebMethod(operationName = "TeeKiinteistonTunnistusKysely", action = "http://tempuri.org/TeeKiinteistonTunnistusKysely")
    @RequestWrapper(localName = "TeeKiinteistonTunnistusKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeKiinteistonTunnistusKysely")
    @ResponseWrapper(localName = "TeeKiinteistonTunnistusKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeKiinteistonTunnistusKyselyResponse")
    @WebResult(name = "TeeKiinteistonTunnistusKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeKiinteistonTunnistusKyselyResponse.TeeKiinteistonTunnistusKyselyResult teeKiinteistonTunnistusKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "HakuXml", targetNamespace = "http://tempuri.org/")
        java.lang.String hakuXml,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );

    @WebMethod(operationName = "HaeTuotteenSkeema", action = "http://tempuri.org/HaeTuotteenSkeema")
    @RequestWrapper(localName = "HaeTuotteenSkeema", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HaeTuotteenSkeema")
    @ResponseWrapper(localName = "HaeTuotteenSkeemaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HaeTuotteenSkeemaResponse")
    @WebResult(name = "HaeTuotteenSkeemaResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.HaeTuotteenSkeemaResponse.HaeTuotteenSkeemaResult haeTuotteenSkeema(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "laji", targetNamespace = "http://tempuri.org/")
        short laji
    );

    @WebMethod(operationName = "TeeHenkilonPoimintaKysely", action = "http://tempuri.org/TeeHenkilonPoimintaKysely")
    @RequestWrapper(localName = "TeeHenkilonPoimintaKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeHenkilonPoimintaKysely")
    @ResponseWrapper(localName = "TeeHenkilonPoimintaKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeHenkilonPoimintaKyselyResponse")
    @WebResult(name = "TeeHenkilonPoimintaKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeHenkilonPoimintaKyselyResponse.TeeHenkilonPoimintaKyselyResult teeHenkilonPoimintaKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "HakuXml", targetNamespace = "http://tempuri.org/")
        java.lang.String hakuXml,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );

    @WebMethod(operationName = "TeeRakennuksenTunnistusKysely", action = "http://tempuri.org/TeeRakennuksenTunnistusKysely")
    @RequestWrapper(localName = "TeeRakennuksenTunnistusKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeRakennuksenTunnistusKysely")
    @ResponseWrapper(localName = "TeeRakennuksenTunnistusKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeRakennuksenTunnistusKyselyResponse")
    @WebResult(name = "TeeRakennuksenTunnistusKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeRakennuksenTunnistusKyselyResponse.TeeRakennuksenTunnistusKyselyResult teeRakennuksenTunnistusKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "HakuXml", targetNamespace = "http://tempuri.org/")
        java.lang.String hakuXml,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );

    @WebMethod(operationName = "TeeKiinteistoTunnusKysely", action = "http://tempuri.org/TeeKiinteistoTunnusKysely")
    @RequestWrapper(localName = "TeeKiinteistoTunnusKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeKiinteistoTunnusKysely")
    @ResponseWrapper(localName = "TeeKiinteistoTunnusKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeKiinteistoTunnusKyselyResponse")
    @WebResult(name = "TeeKiinteistoTunnusKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeKiinteistoTunnusKyselyResponse.TeeKiinteistoTunnusKyselyResult teeKiinteistoTunnusKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "Kiinteistotunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kiinteistotunnus,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );

    @WebMethod(operationName = "TeeHenkilonTunnistusKysely", action = "http://tempuri.org/TeeHenkilonTunnistusKysely")
    @RequestWrapper(localName = "TeeHenkilonTunnistusKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeHenkilonTunnistusKysely")
    @ResponseWrapper(localName = "TeeHenkilonTunnistusKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeHenkilonTunnistusKyselyResponse")
    @WebResult(name = "TeeHenkilonTunnistusKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeHenkilonTunnistusKyselyResponse.TeeHenkilonTunnistusKyselyResult teeHenkilonTunnistusKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "HakuXml", targetNamespace = "http://tempuri.org/")
        java.lang.String hakuXml,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );

    @WebMethod(operationName = "TeeRakennusTunnusKysely", action = "http://tempuri.org/TeeRakennusTunnusKysely")
    @RequestWrapper(localName = "TeeRakennusTunnusKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeRakennusTunnusKysely")
    @ResponseWrapper(localName = "TeeRakennusTunnusKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeRakennusTunnusKyselyResponse")
    @WebResult(name = "TeeRakennusTunnusKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeRakennusTunnusKyselyResponse.TeeRakennusTunnusKyselyResult teeRakennusTunnusKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "Rakennustunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String rakennustunnus,
        @WebParam(name = "Huoneistotunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String huoneistotunnus,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );

    @WebMethod(operationName = "TeeHenkilonTunnusKysely", action = "http://tempuri.org/TeeHenkilonTunnusKysely")
    @RequestWrapper(localName = "TeeHenkilonTunnusKysely", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeHenkilonTunnusKysely")
    @ResponseWrapper(localName = "TeeHenkilonTunnusKyselyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TeeHenkilonTunnusKyselyResponse")
    @WebResult(name = "TeeHenkilonTunnusKyselyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TeeHenkilonTunnusKyselyResponse.TeeHenkilonTunnusKyselyResult teeHenkilonTunnusKysely(
        @WebParam(name = "SoSoNimi", targetNamespace = "http://tempuri.org/")
        java.lang.String soSoNimi,
        @WebParam(name = "Kayttajatunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String kayttajatunnus,
        @WebParam(name = "Salasana", targetNamespace = "http://tempuri.org/")
        java.lang.String salasana,
        @WebParam(name = "Loppukayttaja", targetNamespace = "http://tempuri.org/")
        java.lang.String loppukayttaja,
        @WebParam(name = "Laskutustiedot", targetNamespace = "http://tempuri.org/")
        java.lang.String laskutustiedot,
        @WebParam(name = "Henkilotunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String henkilotunnus,
        @WebParam(name = "SahkoinenAsiointitunnus", targetNamespace = "http://tempuri.org/")
        java.lang.String sahkoinenAsiointitunnus,
        @WebParam(name = "VarmenteenMyontaja", targetNamespace = "http://tempuri.org/")
        java.lang.String varmenteenMyontaja,
        @WebParam(name = "X509Certificate", targetNamespace = "http://tempuri.org/")
        java.lang.String x509Certificate,
        @WebParam(name = "VarmenteenVoimassaolotarkistus", targetNamespace = "http://tempuri.org/")
        java.lang.String varmenteenVoimassaolotarkistus,
        @WebParam(name = "VarmenteenSulkulistatarkistus", targetNamespace = "http://tempuri.org/")
        java.lang.String varmenteenSulkulistatarkistus,
        @WebParam(name = "Tunnistusportaali", targetNamespace = "http://tempuri.org/")
        java.lang.String tunnistusportaali,
        @WebParam(name = "Vara1", targetNamespace = "http://tempuri.org/")
        java.lang.String vara1
    );
}
