
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-06-27T11:40:19.991+03:00
 * Generated source version: 3.0.3
 * 
 */
public final class SoSoSoap_SoSoSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "SoSo");

    private SoSoSoap_SoSoSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SoSo.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SoSo ss = new SoSo(wsdlURL, SERVICE_NAME);
        SoSoSoap port = ss.getSoSoSoap();  
        
        {
        System.out.println("Invoking teeKiinteistonTunnistusKysely...");
        java.lang.String _teeKiinteistonTunnistusKysely_soSoNimi = "";
        java.lang.String _teeKiinteistonTunnistusKysely_kayttajatunnus = "";
        java.lang.String _teeKiinteistonTunnistusKysely_salasana = "";
        java.lang.String _teeKiinteistonTunnistusKysely_loppukayttaja = "";
        java.lang.String _teeKiinteistonTunnistusKysely_laskutustiedot = "";
        java.lang.String _teeKiinteistonTunnistusKysely_hakuXml = "";
        java.lang.String _teeKiinteistonTunnistusKysely_vara1 = "";
        org.tempuri.TeeKiinteistonTunnistusKyselyResponse.TeeKiinteistonTunnistusKyselyResult _teeKiinteistonTunnistusKysely__return = port.teeKiinteistonTunnistusKysely(_teeKiinteistonTunnistusKysely_soSoNimi, _teeKiinteistonTunnistusKysely_kayttajatunnus, _teeKiinteistonTunnistusKysely_salasana, _teeKiinteistonTunnistusKysely_loppukayttaja, _teeKiinteistonTunnistusKysely_laskutustiedot, _teeKiinteistonTunnistusKysely_hakuXml, _teeKiinteistonTunnistusKysely_vara1);
        System.out.println("teeKiinteistonTunnistusKysely.result=" + _teeKiinteistonTunnistusKysely__return);


        }
        {
        System.out.println("Invoking haeTuotteenSkeema...");
        java.lang.String _haeTuotteenSkeema_soSoNimi = "";
        short _haeTuotteenSkeema_laji = Short.parseShort("0");
        org.tempuri.HaeTuotteenSkeemaResponse.HaeTuotteenSkeemaResult _haeTuotteenSkeema__return = port.haeTuotteenSkeema(_haeTuotteenSkeema_soSoNimi, _haeTuotteenSkeema_laji);
        System.out.println("haeTuotteenSkeema.result=" + _haeTuotteenSkeema__return);


        }
        {
        System.out.println("Invoking teeHenkilonPoimintaKysely...");
        java.lang.String _teeHenkilonPoimintaKysely_soSoNimi = "";
        java.lang.String _teeHenkilonPoimintaKysely_kayttajatunnus = "";
        java.lang.String _teeHenkilonPoimintaKysely_salasana = "";
        java.lang.String _teeHenkilonPoimintaKysely_loppukayttaja = "";
        java.lang.String _teeHenkilonPoimintaKysely_laskutustiedot = "";
        java.lang.String _teeHenkilonPoimintaKysely_hakuXml = "";
        java.lang.String _teeHenkilonPoimintaKysely_vara1 = "";
        org.tempuri.TeeHenkilonPoimintaKyselyResponse.TeeHenkilonPoimintaKyselyResult _teeHenkilonPoimintaKysely__return = port.teeHenkilonPoimintaKysely(_teeHenkilonPoimintaKysely_soSoNimi, _teeHenkilonPoimintaKysely_kayttajatunnus, _teeHenkilonPoimintaKysely_salasana, _teeHenkilonPoimintaKysely_loppukayttaja, _teeHenkilonPoimintaKysely_laskutustiedot, _teeHenkilonPoimintaKysely_hakuXml, _teeHenkilonPoimintaKysely_vara1);
        System.out.println("teeHenkilonPoimintaKysely.result=" + _teeHenkilonPoimintaKysely__return);


        }
        {
        System.out.println("Invoking teeRakennuksenTunnistusKysely...");
        java.lang.String _teeRakennuksenTunnistusKysely_soSoNimi = "";
        java.lang.String _teeRakennuksenTunnistusKysely_kayttajatunnus = "";
        java.lang.String _teeRakennuksenTunnistusKysely_salasana = "";
        java.lang.String _teeRakennuksenTunnistusKysely_loppukayttaja = "";
        java.lang.String _teeRakennuksenTunnistusKysely_laskutustiedot = "";
        java.lang.String _teeRakennuksenTunnistusKysely_hakuXml = "";
        java.lang.String _teeRakennuksenTunnistusKysely_vara1 = "";
        org.tempuri.TeeRakennuksenTunnistusKyselyResponse.TeeRakennuksenTunnistusKyselyResult _teeRakennuksenTunnistusKysely__return = port.teeRakennuksenTunnistusKysely(_teeRakennuksenTunnistusKysely_soSoNimi, _teeRakennuksenTunnistusKysely_kayttajatunnus, _teeRakennuksenTunnistusKysely_salasana, _teeRakennuksenTunnistusKysely_loppukayttaja, _teeRakennuksenTunnistusKysely_laskutustiedot, _teeRakennuksenTunnistusKysely_hakuXml, _teeRakennuksenTunnistusKysely_vara1);
        System.out.println("teeRakennuksenTunnistusKysely.result=" + _teeRakennuksenTunnistusKysely__return);


        }
        {
        System.out.println("Invoking teeKiinteistoTunnusKysely...");
        java.lang.String _teeKiinteistoTunnusKysely_soSoNimi = "";
        java.lang.String _teeKiinteistoTunnusKysely_kayttajatunnus = "";
        java.lang.String _teeKiinteistoTunnusKysely_salasana = "";
        java.lang.String _teeKiinteistoTunnusKysely_loppukayttaja = "";
        java.lang.String _teeKiinteistoTunnusKysely_laskutustiedot = "";
        java.lang.String _teeKiinteistoTunnusKysely_kiinteistotunnus = "";
        java.lang.String _teeKiinteistoTunnusKysely_vara1 = "";
        org.tempuri.TeeKiinteistoTunnusKyselyResponse.TeeKiinteistoTunnusKyselyResult _teeKiinteistoTunnusKysely__return = port.teeKiinteistoTunnusKysely(_teeKiinteistoTunnusKysely_soSoNimi, _teeKiinteistoTunnusKysely_kayttajatunnus, _teeKiinteistoTunnusKysely_salasana, _teeKiinteistoTunnusKysely_loppukayttaja, _teeKiinteistoTunnusKysely_laskutustiedot, _teeKiinteistoTunnusKysely_kiinteistotunnus, _teeKiinteistoTunnusKysely_vara1);
        System.out.println("teeKiinteistoTunnusKysely.result=" + _teeKiinteistoTunnusKysely__return);


        }
        {
        System.out.println("Invoking teeHenkilonTunnistusKysely...");
        java.lang.String _teeHenkilonTunnistusKysely_soSoNimi = "";
        java.lang.String _teeHenkilonTunnistusKysely_kayttajatunnus = "";
        java.lang.String _teeHenkilonTunnistusKysely_salasana = "";
        java.lang.String _teeHenkilonTunnistusKysely_loppukayttaja = "";
        java.lang.String _teeHenkilonTunnistusKysely_laskutustiedot = "";
        java.lang.String _teeHenkilonTunnistusKysely_hakuXml = "";
        java.lang.String _teeHenkilonTunnistusKysely_vara1 = "";
        org.tempuri.TeeHenkilonTunnistusKyselyResponse.TeeHenkilonTunnistusKyselyResult _teeHenkilonTunnistusKysely__return = port.teeHenkilonTunnistusKysely(_teeHenkilonTunnistusKysely_soSoNimi, _teeHenkilonTunnistusKysely_kayttajatunnus, _teeHenkilonTunnistusKysely_salasana, _teeHenkilonTunnistusKysely_loppukayttaja, _teeHenkilonTunnistusKysely_laskutustiedot, _teeHenkilonTunnistusKysely_hakuXml, _teeHenkilonTunnistusKysely_vara1);
        System.out.println("teeHenkilonTunnistusKysely.result=" + _teeHenkilonTunnistusKysely__return);


        }
        {
        System.out.println("Invoking teeRakennusTunnusKysely...");
        java.lang.String _teeRakennusTunnusKysely_soSoNimi = "";
        java.lang.String _teeRakennusTunnusKysely_kayttajatunnus = "";
        java.lang.String _teeRakennusTunnusKysely_salasana = "";
        java.lang.String _teeRakennusTunnusKysely_loppukayttaja = "";
        java.lang.String _teeRakennusTunnusKysely_laskutustiedot = "";
        java.lang.String _teeRakennusTunnusKysely_rakennustunnus = "";
        java.lang.String _teeRakennusTunnusKysely_huoneistotunnus = "";
        java.lang.String _teeRakennusTunnusKysely_vara1 = "";
        org.tempuri.TeeRakennusTunnusKyselyResponse.TeeRakennusTunnusKyselyResult _teeRakennusTunnusKysely__return = port.teeRakennusTunnusKysely(_teeRakennusTunnusKysely_soSoNimi, _teeRakennusTunnusKysely_kayttajatunnus, _teeRakennusTunnusKysely_salasana, _teeRakennusTunnusKysely_loppukayttaja, _teeRakennusTunnusKysely_laskutustiedot, _teeRakennusTunnusKysely_rakennustunnus, _teeRakennusTunnusKysely_huoneistotunnus, _teeRakennusTunnusKysely_vara1);
        System.out.println("teeRakennusTunnusKysely.result=" + _teeRakennusTunnusKysely__return);


        }
        {
        System.out.println("Invoking teeHenkilonTunnusKysely...");
        java.lang.String _teeHenkilonTunnusKysely_soSoNimi = "";
        java.lang.String _teeHenkilonTunnusKysely_kayttajatunnus = "";
        java.lang.String _teeHenkilonTunnusKysely_salasana = "";
        java.lang.String _teeHenkilonTunnusKysely_loppukayttaja = "";
        java.lang.String _teeHenkilonTunnusKysely_laskutustiedot = "";
        java.lang.String _teeHenkilonTunnusKysely_henkilotunnus = "";
        java.lang.String _teeHenkilonTunnusKysely_sahkoinenAsiointitunnus = "";
        java.lang.String _teeHenkilonTunnusKysely_varmenteenMyontaja = "";
        java.lang.String _teeHenkilonTunnusKysely_x509Certificate = "";
        java.lang.String _teeHenkilonTunnusKysely_varmenteenVoimassaolotarkistus = "";
        java.lang.String _teeHenkilonTunnusKysely_varmenteenSulkulistatarkistus = "";
        java.lang.String _teeHenkilonTunnusKysely_tunnistusportaali = "";
        java.lang.String _teeHenkilonTunnusKysely_vara1 = "";
        org.tempuri.TeeHenkilonTunnusKyselyResponse.TeeHenkilonTunnusKyselyResult _teeHenkilonTunnusKysely__return = port.teeHenkilonTunnusKysely(_teeHenkilonTunnusKysely_soSoNimi, _teeHenkilonTunnusKysely_kayttajatunnus, _teeHenkilonTunnusKysely_salasana, _teeHenkilonTunnusKysely_loppukayttaja, _teeHenkilonTunnusKysely_laskutustiedot, _teeHenkilonTunnusKysely_henkilotunnus, _teeHenkilonTunnusKysely_sahkoinenAsiointitunnus, _teeHenkilonTunnusKysely_varmenteenMyontaja, _teeHenkilonTunnusKysely_x509Certificate, _teeHenkilonTunnusKysely_varmenteenVoimassaolotarkistus, _teeHenkilonTunnusKysely_varmenteenSulkulistatarkistus, _teeHenkilonTunnusKysely_tunnistusportaali, _teeHenkilonTunnusKysely_vara1);
        System.out.println("teeHenkilonTunnusKysely.result=" + _teeHenkilonTunnusKysely__return);


        }

        System.exit(0);
    }

}
