package org.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-06-27T11:40:20.043+03:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "SoSo", 
                  wsdlLocation = "TestiIP.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class SoSo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SoSo");
    public final static QName SoSoSoap = new QName("http://tempuri.org/", "SoSoSoap");
    public final static QName SoSoSoap12 = new QName("http://tempuri.org/", "SoSoSoap12");
    static {
        URL url = SoSo.class.getResource("TestiIP.wsdl");
        if (url == null) {
            url = SoSo.class.getClassLoader().getResource("TestiIP.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(SoSo.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "TestiIP.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SoSo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoSo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoSo() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoSo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoSo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoSo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SoSoSoap
     */
    @WebEndpoint(name = "SoSoSoap")
    public SoSoSoap getSoSoSoap() {
        return super.getPort(SoSoSoap, SoSoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoSoSoap
     */
    @WebEndpoint(name = "SoSoSoap")
    public SoSoSoap getSoSoSoap(WebServiceFeature... features) {
        return super.getPort(SoSoSoap, SoSoSoap.class, features);
    }
    /**
     *
     * @return
     *     returns SoSoSoap
     */
    @WebEndpoint(name = "SoSoSoap12")
    public SoSoSoap getSoSoSoap12() {
        return super.getPort(SoSoSoap12, SoSoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoSoSoap
     */
    @WebEndpoint(name = "SoSoSoap12")
    public SoSoSoap getSoSoSoap12(WebServiceFeature... features) {
        return super.getPort(SoSoSoap12, SoSoSoap.class, features);
    }

}
