//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.05 at 03:12:10 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://x-road.eu/xsd/identifiers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xroad.xml.xrd;
